language: go
sudo: required
dist: trusty

services:
  - docker

go:
 - 1.8.1

addons:
   apt:

env:
  global:
    - TOOLS_CMD=golang.org/x/tools/cmd
    - PATH=$GOROOT/bin:$PATH
    - SUDO_PERMITTED=1

before_install:
  - go get -u gopkg.in/alecthomas/gometalinter.v1
  - go get -v github.com/Masterminds/glide
  - gometalinter.v1 --install
  - make codegen

install:
  - mkdir -p $GOPATH/src/github.com/docker && cd $GOPATH/src/github.com/docker && git clone https://github.com/docker/docker -b 1.13.x docker && cd -
  - glide up


script:
  - gometalinter.v1 --disable-all --enable=vet --enable=vetshadow --enable=errcheck --enable=golint --enable=structcheck --enable=aligncheck --enable=deadcode --enable=ineffassign --enable=gotype --enable=goimports --enable=varcheck --enable=interfacer --enable=goconst --enable=gosimple --enable=staticcheck --enable=unused --enable=misspell --deadline=5m --vendor --exclude=vendor ./...
  - make build


after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - 'if [ ${TRAVIS_BRANCH} = "master" ] && [ ${TRAVIS_PULL_REQUEST} = "false" ]; then
      make docker_push;
    fi'
  - make docker_push -e DOCKER_IMAGE_TAG="${TRAVIS_COMMIT}"
