FROM ubuntu
MAINTAINER Bernard Van De Walle <bernard@aporeto.com>

RUN mkdir -p /opt/trireme/trireme-statistics

ADD trireme-statistics /opt/trireme/trireme-statistics

WORKDIR /opt/trireme/trireme-statistics

CMD ["./trireme-statistics"]
