apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  creationTimestamp: null
  labels:
    app: aporeto-collector
  name: aporeto-collector
  namespace: kube-system
spec:
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aporeto-collector
    spec:
      containers:
        image: aporeto/trireme-collector:latest
        imagePullPolicy: Always
        name: kube-squall
        resources: {}
status:
  replicas: 0
---
kind: Service
apiVersion: v1
metadata:
  name: collector
  namespace: kube-system
spec:
  selector:
    role: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
